### PR TITLE
Fixes #125: Avoid error with "~" path in WebPack preventing use of nu…

### LINKED ISSUE #125: [nuxt] Nuxt-i18n integration with lazy mode does not build
Hello there,

First, thanks for your work on this library, I discovered it yesterday and it looks very promising.

I am trying to migrate one of my Nuxt projects to Nx thanks to the plugin, and there is one last error that I can't get rid of. I would be happy to help solving it but I'm not really able to understand alone what would be the best way.

## Steps to Reproduce
1. Generate a fresh app with `nx g @nx-plus/nuxt:app my-app`
2. Install nuxt-i18n : `npm i nuxt-i18n --save`
3. Add nuxt-i18n to the nuxt.config.ts :  `modules: ['nuxt-i18n'],`
4. Create a `./locales/en/index.ts` file in the Nuxt app with content: `export default {}`
5. Configure lazy mode for nuxt-i18n in nuxt.config.ts:
```
i18n: {
    locales: [
      {
        code: 'en',
        file: 'en/index.ts'
      }
    ],
    defaultLocale: 'en',
    lazy: true,
    langDir: 'locales/',
    strategy: 'no_prefix'
  },
```
6. Attempt to serve the application: `nx serve my-app`

## Current Behavior
Using nuxt-i18n inside the Nuxt application with lazy mode triggers an error that prevents compilation:
```
 ERROR  Failed to compile with 1 errors

This dependency was not found:          

* ~/lang in ./dist/apps/my-app/nuxt-i18n/utils.js
To install it, you can run: npm install --save ~/lang
```

## Expected Behavior
The project compiles without any problem.

### Environment

Plugin name and version: @nx-plus/nuxt v10.2.0

nx report:
```
  nx : Not Found
  @nrwl/angular : Not Found
  @nrwl/cli : 10.4.4
  @nrwl/cypress : 10.4.4
  @nrwl/eslint-plugin-nx : 10.4.4
  @nrwl/express : Not Found
  @nrwl/jest : 10.4.4
  @nrwl/linter : 10.4.4
  @nrwl/nest : 10.4.4
  @nrwl/next : Not Found
  @nrwl/node : 10.4.4
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 10.4.4
  @nrwl/web : Not Found
  @nrwl/workspace : 10.4.4
  typescript : 4.0.5
```

Thanks for your help!

### PR DESCRIPTION
**Pull request by KennyDurand**
…xt-i18n

## Related Issue(s)

Fixes #125

### CODE REVIEW

File: libs/nuxt/src/webpack.ts [hunk 1]
```diff
@@ -3,7 +3,7 @@ import TsconfigPathsPlugin from 'tsconfig-paths-webpack-plugin';
 
 // eslint-disable-next-line @typescript-eslint/no-explicit-any
 export function modifyTypescriptAliases(config: any, projectRoot: Path): void {
-  ['~~', '@@', '~', '@', 'assets', 'static'].forEach(
+  ['~~', '@@', '@', 'assets', 'static'].forEach(
```
Comment (BuckyMaler) [inline libs/nuxt/src/webpack.ts:6]: This fixes the compilation error, but like I mentioned [here](https://github.com/ZachJW34/nx-plus/issues/125#issuecomment-731704018) please remove all of the aliases.

**Review by BuckyMaler — CHANGES_REQUESTED** [review]
This isn't an issue with the latest version of `nuxt-i18n` because it no longer has a dependency on the `~` alias, but I think this change should still be made.

**Review by BuckyMaler — APPROVED** [review]

**Comment by BuckyMaler** [comment]
@KennyDurand thanks!
